package com.cs.hit.thinkinginjava.exception.example.ex4;

public class NoExcprion {
    public void f() throws Exception {
        throw new RuntimeException("I am Exception in f()");
    }
}
